---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 12:00
---

__GEInitTable__ = __GEInitTable__ or {}

local gesocket = CS.CSharp.GESocket

print(gesocket.Instance().Connect(gesocket.Instance(), "127.0.0.1", 10086))

return __GEInitTable__