---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 12:00
---

__GEInitTable__ = __GEInitTable__ or {}

function __GEInitTable__.Init()
    __GEInitTable__.load_all_script()
    require("GameObjectScript/GOAddScriptExample")
    
end

function __GEInitTable__.first_load_script()
end

function __GEInitTable__.load_all_script()
    __GEInitTable__.first_load_script()
    
    CS.CSharp.LuaHelp.LoadPackageAllScript("Common")
    CS.CSharp.LuaHelp.LoadPackageAllScript("Game")
    CS.CSharp.LuaHelp.LoadPackageAllScript("UI")

end


if __GEInitTable__.is_init ~= true then
    __GEInitTable__.is_init = true
    __GEInitTable__.Init()
end

return __GEInitTable__