---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 12:00
---

__GEInitTable__ = __GEInitTable__ or {}

local MainPanel = require("UI/MainPanel/MainPanel")

MainPanel:show()
MainPanel:after_create()
MainPanel:after_show()

return __GEInitTable__