---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/10 10:57
---

local cube = CS.UnityEngine.GameObject.Find('Cube')
local lua_script = require("GameObjectScript/GOScriptExample")
local script = cube:AddComponent(typeof(CS.CSharp.LuaBehaviour))
script:SetLuaTable(lua_script)

