---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/10 10:52
---

local script_example = {}

function script_example:Awake()
    self = script_example.self
end

function script_example:Start()
    math.randomseed(os.time())

    local role = CS.CSharp.LuaHelp.LoadPrefab("unitychan_dynamic")
    role.name = "unitychan_dynamic"
    
    self = script_example.self
    role.transform:SetParent(self.gameObject.transform)
end

function script_example:Update()
    -- TODO 
    self = script_example.self
    local go = self.gameObject
    local transform = go.transform
    local v3 = transform.position
    v3.x = v3.x + 0.1
    transform.position = v3
    
    local role = transform:Find("unitychan_dynamic")
    local ani = role:GetComponent(typeof(CS.UnityEngine.Animator))
    local pose_index = math.random(1, 31)
    local pose_index_str = string.format("%02d", pose_index)
    local pose = "POSE" .. pose_index_str
    ani:Play(pose)
end 

function script_example:OnDestroy()
    self = script_example.self
end

return script_example