---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/10 10:52
---

local script_example = {}

function script_example:Awake()
end

function script_example:Start()
    
    
    math.randomseed(os.time())

    -- 同步加载
    --local role = CS.CSharp.LuaHelp.LoadPrefab("unitychan_dynamic")
    --role.name = "unitychan_dynamic"
    --
    --self = script_example.self
    --role.transform:SetParent(self.gameObject.transform)
    -- 异步加载
    CS.CSharp.LuaHelp.LoadPrefabAsync("unitychan_dynamic", self, self.load_prefab_callback)
end

function script_example:load_prefab_callback(gameObject)
    print("script_example:load_prefab_callbac")
    print(self)
    print(self.this)
    print(gameObject)
end

function script_example:Update()
    -- TODO 
    --self = script_example.self
    local go = self.this.gameObject
    local transform = go.transform
    local v3 = transform.position
    v3.x = v3.x + 0.1
    transform.position = v3

    local role = transform:Find("unitychan_dynamic")
    if role == nil then
        return
    end
    local ani = role:GetComponent(typeof(CS.UnityEngine.Animator))
    local pose_index = math.random(1, 31)
    local pose_index_str = string.format("%02d", pose_index)
    local pose = "POSE" .. pose_index_str
    --ani:Play(pose)
    ani.speed = 0.3
    if pose_index > 20 then
        ani:SetBool("Next", true)
        ani:SetBool("Back", false)
    elseif pose_index <= 10then
        ani:SetBool("Next", false)
        ani:SetBool("Back", true)
    else
        ani:SetBool("Next", false)
        ani:SetBool("Back", false)
    end
end 

function script_example:OnDestroy()
    --self = script_example.self
end

return script_example