---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 15:55
---

__UIBaseTable__ = __UIBaseTable__ or {}


function __UIBaseTable__:show()
    if(self.isShow == true) then
        return
    end
    CS.CSharp.Game.GEUI.instance().ShowUIPanel(self.panelName, self.pkgName, self.comName)
    self.isShow = true
end

function __UIBaseTable__:hide()
    if(self.isShow == false) then
        return
    end
    CS.CSharp.Game.GEUI.instance().HideUIPanel(self.panelName)
    self.isShow = false
end


function __UIBaseTable__:new(panelName, pkgName, comName)
    local o = {
        panelName = panelName,
        pkgName = pkgName,
        comName = comName,
        isShow = false
    }
    setmetatable(o, {__index = self})
end 