---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/12 14:25
---
---
---


__UIBaseTable__ = __UIBaseTable__ or {}

function __UIBaseTable__:get_component(...)
    local component = select(1, ...)
    if type(component) ~= "userdata" then
        component = self:get_child(...)
    end
    return component
end

function __UIBaseTable__:bind_click_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onClick', 0, 0)
end

function __UIBaseTable__:bind_touch_begin_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onTouchBegin', 0, 0)
end

function __UIBaseTable__:bind_touch_move_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onTouchMove', 0, 0)
end

function __UIBaseTable__:bind_touch_end_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onTouchEnd', 0, 0)
end

function __UIBaseTable__:bind_drag_move_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onDragMove', 0, 0)
end

function __UIBaseTable__:bind_scroll_delegate(lua_function, ...)
    local component = self:get_component(...)
    scroll_pane = component.scrollPane
    return self:bind_event_delegate(lua_function, scroll_pane, 'onScroll', 0, 0)
end

function __UIBaseTable__:bind_onchange_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onChanged', 0, 0)
end

function __UIBaseTable__:bind_focus_out_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, 'onFocusOut', 0, 0)
end


function __UIBaseTable__:bind_event_delegate(lua_function, component, event_type, param1, param2)
    local listener = component[event_type]
    if listener == nil then
        print("bind_event_delegate error listener nil" .. component.name .. event_type)
    end
    local delegate_proxy = CS.CSharp.BindLuaEvent.BindLuaEventFun(self, listener, lua_function, param1, param2)
    if delegate_proxy == nil then
        print("bind_event_delegate error proxy nil" .. event_type)
    end
    return delegate_proxy
end

return __UIBaseTable__