---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/12 14:25
---
---
---


__UIBaseTable__ = __UIBaseTable__ or {}

function __UIBaseTable__:get_component(...)
    local component = select(1, ...)
    if type(component) ~= "userdata" then
        component = self:get_child(...)
    end
    return component
end

function __UIBaseTable__:bind_click_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, "onClick")
end

function __UIBaseTable__:bind_onchange_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, "onChanged")
end

function __UIBaseTable__:bind_focus_out_delegate(lua_function, ...)
    local component = self:get_component(...)
    return self:bind_event_delegate(lua_function, component, "onFocusOut")
end


function __UIBaseTable__:bind_event_delegate(lua_function, component, event_type)
    if component == nil then
        print("bind_event_delegate error component nil")
        return nil
    end
    local delegate_proxy = CS.CSharp.BindLuaEvent.BindLuaEventFun(self, component, lua_function, event_type)
    if delegate_proxy == nil then
    end
    return delegate_proxy
end

return __UIBaseTable__