---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 15:58
---

local uibase = require("UI/UIBase/UIBase")

__MainPanelTable__ = __MainPanelTable__ or uibase:new("MainPanel", "main", "main_panel")

function __MainPanelTable__:after_create()
    self.btn_1 = self:get_child("btn_1")
    self.btn_2 = self:get_child("btn_2")
    self.input = self:get_child("input")
    self.title = self:get_child("title")
    self.item_joystick = self:get_child("item_joystick")
    self.joystick = self.item_joystick:GetChild("joystick")
    self.touch_joystick = self.item_joystick:GetChild("touch_joystick")
    self:bind_click_delegate(self.click_btn_1, self.btn_1)
    self:bind_click_delegate(self.click_btn_2, "btn_2")
    self:bind_focus_out_delegate(self.input_change, self.input)
    self:bind_scroll_delegate(self.touch_joystick_move, self.item_joystick)
end

function __MainPanelTable__:after_show()
    self.title.text = "这是测试标题"
end

function __MainPanelTable__:click_btn_1(ctx)
    print("click_btn_1")
    print(ctx.sender)
end

function __MainPanelTable__:click_btn_2()
    print("click_btn_2")
    print("输入文本为" .. self.input.text)
end

function __MainPanelTable__:input_change()
    print("__MainPanelTable__:input_change")
end

function __MainPanelTable__:touch_joystick_move()
    print("__MainPanelTable__:touch_joystick_move")
    print(self.item_joystick.scrollPane)
end

local function open_main_panel()
    local uiMgr = require("UI/UIMgr")
    uiMgr.show_panel(__MainPanelTable__.panelName)
end

local function init()
    local gevent = require("Game/GEvent")
    gevent.reg_event(gevent.AfterLoadAllScripts, open_main_panel)
end

if __MainPanelTable__.is_init == nil then
    __MainPanelTable__.is_init = nil
    init()
end

return __MainPanelTable__