---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lsjlkz.
--- DateTime: 2023/5/5 15:58
---

local uibase = require("UI/UIBase/UIBase")

__MainPanelTable__ = __MainPanelTable__ or {
    myPanel = uibase:new("MainPanel", "Basics", "Main")
}

function __MainPanelTable__:show()
    self.myPanel:show()
end


return __MainPanelTable__